# Every hard limit of the language and the toolchain, shown by a case that just
# fits and a case that just does not.  Prints a table; fails when a limit moved
# without this file being updated.  See README.md next to this file.
. "$ROOT/tests/helpers.sh"
fails=0
row() { printf '  %-44s %-10s %s\n' "$1" "$2" "$3"; }
expect_compile() {   # name file
  if "$WANTZEL" "$2" "$T/bin" >"$T/err" 2>&1; then row "$1" "compiles" "ok"; else row "$1" "NO" "$(head -c 80 "$T/err")"; fails=$((fails+1)); fi; }
expect_fail() {      # name file message
  if "$WANTZEL" "$2" "$T/bin" >"$T/err" 2>&1; then row "$1" "compiles" "UNEXPECTED"; fails=$((fails+1));
  elif grep -q "$3" "$T/err"; then row "$1" "refused" "ok: $3"; else row "$1" "refused" "WRONG MESSAGE: $(head -c 80 "$T/err")"; fails=$((fails+1)); fi; }
expect_run() {       # name file expected-rc
  "$WANTZEL" "$2" "$T/bin" >"$T/err" 2>&1 || { row "$1" "NO" "$(head -c 80 "$T/err")"; fails=$((fails+1)); return; }
  (cd "$T" && ./bin >/dev/null 2>&1); rc=$?
  if [ "$rc" = "$3" ]; then row "$1" "rc=$rc" "ok"; else row "$1" "rc=$rc" "expected rc=$3"; fails=$((fails+1)); fi; }
# The test programs are generated by a Wantzel program, not by another language: a
# suite that needs python3 to produce its own inputs sits badly with a compiler whose
# claim is that it needs nothing.  progs/gen.wz takes the kind and the count; the
# knowledge of what each limit IS stays here, in the calls below.
GEN="$T/gen"
"$WANTZEL" "$ROOT/tests/limits/progs/gen.wz" "$GEN" >"$T/generr" 2>&1 || {
  echo "the generator does not compile:"; cat "$T/generr"; exit 1; }
gen() { "$GEN" "$1" "$2" "$T/$3" "$ROOT" || { echo "gen $1 $2 failed"; exit 1; }; }

echo "limits of the toolchain"
# routine arguments: 10 (an array counts as two)
gen params 10 p10.wz
gen params 11 p11.wz
expect_compile "10 arguments" "$T/p10.wz"; expect_fail "11 arguments" "$T/p11.wz" "at most ten arguments"
# identifier and string literal length: TBMAX-1 = 4095
gen ident 4095 id4095.wz
gen ident 4096 id4096.wz
expect_compile "identifier of 4095 chars" "$T/id4095.wz"; expect_fail "identifier of 4096 chars" "$T/id4096.wz" "identifier too long"
gen strlit 4095 s4095.wz
gen strlit 4096 s4096.wz
expect_compile "string literal of 4095 bytes" "$T/s4095.wz"; expect_fail "string literal of 4096 bytes" "$T/s4096.wz" "string literal too long"
# include depth: 16
# A chain of files each including the next.  Plain sh: this makes directories and one
# small file per level, which needs no generator.
mktree() {   # depth name
  mkdir -p "$T/$2"
  i=1
  while [ $i -le $1 ]; do
    if [ $i -lt $1 ]; then printf 'include "l%d.wz";\n' $((i + 1)) > "$T/$2/l$i.wz"
    else : > "$T/$2/l$i.wz"; fi
    printf 'var v%d: int;\n' $i >> "$T/$2/l$i.wz"
    i=$((i + 1))
  done
  printf 'program t;\ninclude "%s/l1.wz";\nbegin end.\n' "$2" > "$T/$2.wz"
}
mktree 16 inc16
mktree 17 inc17
expect_compile "16 nested includes" "$T/inc16.wz"; expect_fail "17 nested includes" "$T/inc17.wz" "nested too deeply"
# globals: MAXG = 16384 (the schema and tool constants count too)
gen globals 16384 g16384.wz
gen globals 16385 g16385.wz
expect_compile "16384 globals" "$T/g16384.wz"; expect_fail "16385 globals" "$T/g16385.wz" "too many globals"
# locals: MAXL = 2048 (parameters and hidden case/for slots do not count; consts do)
gen locals 2048 l2048.wz
gen locals 2049 l2049.wz
expect_compile "2048 locals" "$T/l2048.wz"; expect_fail "2049 locals" "$T/l2049.wz" "too many locals"
# routines: MAXF = 8192
gen routines 8192 f8192.wz
gen routines 8193 f8193.wz
expect_compile "8192 routines" "$T/f8192.wz"; expect_fail "8193 routines" "$T/f8193.wz" "too many routines"
# record fields per declaration list: 64 names in one declaration
gen fields 64 rf64.wz
gen fields 65 rf65.wz
expect_compile "64 names in one field declaration" "$T/rf64.wz"; expect_fail "65 names in one field declaration" "$T/rf65.wz" "too many names"
# schema fields: MAXFLD = 128
gen schemafields 128 sf128.wz
gen schemafields 129 sf129.wz
expect_compile "128 schema fields" "$T/sf128.wz"; expect_fail "129 schema fields" "$T/sf129.wz" "too many fields"
# schemas: MAXS = 512
gen schemas 512 sc512.wz
gen schemas 513 sc513.wz
expect_compile "512 schemas" "$T/sc512.wz"; expect_fail "513 schemas" "$T/sc513.wz" "too many schemas"
# tools: MAXT = 1024 (each tool also needs a handler)
gen tools 1024 t1024.wz
gen toolsonly 1025 t1025.wz
expect_compile "1024 tools" "$T/t1024.wz"; expect_fail "1025 tools" "$T/t1025.wz" "too many tools"
# data segment: DATMAX = 32 MB of literals, JSON schemas and the tool list.  A literal of
# 4000 bytes costs 4016 (the bytes, a nul, an eight-byte length, rounded up to eight), so
# 8355 of them fit and 8356 do not.  The point of this pair is not the number but the
# SHAPE of the refusal: the room must be checked BEFORE the byte is written, otherwise the
# compiler stops on its own bounds check and reports itself instead of the source.
gen datseg 8355 d8355.wz
gen datseg 8356 d8356.wz
expect_compile "32 MB of string literals" "$T/d8355.wz"; expect_fail "just over 32 MB of string literals" "$T/d8356.wz" "data segment overflow: the source is too large"

echo "limits of a running program"
# static memory: bss grows for free until it is touched; the kernel refuses more than RAM+swap (heuristic overcommit) with a segfault at the first touch
gen bss 1073741824 bss1g.wz
expect_run "1 GB static array, touched" "$T/bss1g.wz" 0
# stack: 8 MB by default (ulimit -s); a frame of 64 bytes gives ~120k levels, deeper crashes with SIGSEGV (139), no runtime message
gen recurse 100000 rec100k.wz
gen recurse 1000000 rec1m.wz
expect_run "recursion depth 100000" "$T/rec100k.wz" 0; expect_run "recursion depth 1000000 (stack overflow)" "$T/rec1m.wz" 139
# int overflow wraps silently
# Fixed text with nothing repeated in it, so a heredoc says it more plainly than a
# generator call would.
cat > "$T/wrap.wz" <<EOF
program t;
include "$ROOT/lib/io.wz";
var i: int;
begin i := 9223372036854775807; i := i + 1; if i < 0 then halt(0); halt(1); end.
EOF
expect_run "int overflow wraps (no check)" "$T/wrap.wz" 0
[ $fails -eq 0 ] || { echo "$fails limit checks failed"; exit 1; }
